librarygadget/urls.py
from django.conf.urls.defaults import *
from django.contrib import admin
import django
import os
import django.contrib.auth.views

# Django settings for djangolibrarybot project.
DJANGO_ROOT = os.path.dirname(os.path.realpath(django.__file__))
SITE_ROOT = os.path.dirname(os.path.realpath(__file__))

admin.autodiscover()

urlpatterns = patterns('',

    # Uncomment the admin/doc line below and add 'django.contrib.admindocs' 
    # to INSTALLED_APPS to enable admin documentation:
    #(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    (r'^librarybot/', include('librarybot.urlsapi')),	
    (r'^booklookup/', include('booklookup.urls')),
    (r'^share/', include('share.urls')),
    (r'^admin/', include(admin.site.urls)),
    (r'^', include('librarybot.urlsui')),

    # Paypal
     (r'^ipny283fih92$', include('paypal.standard.ipn.urls')),

    # Registration
    url(r'^accounts/login/$', 'django.contrib.auth.views.login'),
    url(r'^accounts/logout/$', 'django.contrib.auth.views.logout'),
    url(r'^accounts/profile/$', 'librarybot.viewsui.profile'),

    # Home page
    url(r'^$', 'librarybot.viewsui.home', name='home'),

)

librarygadget/librarybot/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Q

from paypal.standard.ipn.signals import payment_was_successful

import os
import base64
import hashlib
import logging
import datetime
import json

import librarybot.gmail
import horizon
import polaris
import sirsidynix
import opac
import webpacpro
import koha

class UserProfile(models.Model):
    user = models.OneToOneField(User)
    api_key = models.CharField(max_length=128, null=True, blank=True)
    ACCOUNT_LEVEL = (
        ('free', 'Free'),
        ('paid', 'Paid')
    )
    account_level = models.CharField(max_length=10, choices=ACCOUNT_LEVEL,  default='free')

    def get_patrons(self):
        patrons = Patron.objects.filter(user=self.user)
        patrons = patrons.filter(inactive=False)
        #patrons = patrons.order_by('library', 'patronid')
        return patrons

    def get_patron_by_id(self, patronid):
        patrons = Patron.objects.filter(user=self.user)
        patrons = patrons.filter(inactive=False)
        patrons = patrons.filter(patronid=patronid)
        #patrons = patrons.order_by('library', 'patronid')
        if len(patrons) == 0:
            logging.warn('No patrons found with id ' + patronid)
            return None
        return patrons[0]

    def create_api_key(self):
        self.api_key = base64.b32encode(os.urandom(32)).strip('=')


class Library(models.Model):
    name = models.CharField(max_length=100)
    state = models.CharField(max_length=2)
    regional_system = models.ForeignKey('self', default=None, null=True, blank=True)
    catalogurl = models.URLField(null=True, blank=True)
    LIBRARY_SYSTEMS = (
        ('ipac', 'Horizon'),
        ('webpacpro', 'WebPac Pro'),
        ('opac', 'Opac'),
        ('sirsidynix', 'Sirsi Dynix'),
        ('polaris', 'Polaris'),
        ('koha', 'Koha')
    )
    librarysystem = models.CharField(max_length=20, choices=LIBRARY_SYSTEMS, null=True, blank=True)
    RENEW_SUPPORTED = (
        ('tested', 'Tested'),
        ('unavailable', 'Unavailable'),
        ('untested', 'Untested')
    )
    renew_supported_code = models.CharField(max_length=10, choices=RENEW_SUPPORTED, default='untested')
    active = models.BooleanField(default=True)
    lastmodified = models.DateField(auto_now=True)
    pin_required = models.BooleanField(default=True)

    def get_absolute_url(self):
        return "/library/%i/" % self.id

    def __str__(self):
        return self.name

    def get_catalog_url(self):
        if self.regional_system is not None:
            return self.regional_system.catalogurl
        return self.catalogurl

    def get_library_system(self):
        if self.regional_system is not None:
            return self.regional_system.librarysystem
        return self.librarysystem


class Patron(models.Model): 
    library = models.ForeignKey(Library)
    user = models.ForeignKey(User, null=True) #Patrons aren't required to have a User (yet)
    patronid = models.CharField(max_length=40, verbose_name='Library card number')
    pin = models.CharField(max_length=75, verbose_name='Library website password')
    name = models.CharField(max_length=150, null=True, blank=True, verbose_name='Name on library card')
    save_history = models.BooleanField()
    lastchecked = models.DateTimeField(auto_now=False)
    batch_last_run = models.DateField(null=True, blank=True)
    inactive = models.BooleanField()

    #def __str__(self):
    #	return self.patronid

    def get_bot(self, password='', name=''):
        password = password.strip()
        name = name.strip()

        logging.debug("get_bot for %s (%s) using %s" % (self.library.name, self.library.get_catalog_url(), self.library.get_library_system()))
        if self.library.get_library_system() == 'ipac':
            return horizon.LibraryBot(self.library.get_catalog_url(), self.patronid, password, name)
        if self.library.get_library_system() == "sirsidynix":
            return sirsidynix.LibraryBot(self.library.get_catalog_url(), self.patronid, password, name)
        if self.library.get_library_system() == 'opac':
            return opac.LibraryBot(self.library.get_catalog_url(), self.patronid, password, name)
        if self.library.get_library_system() == 'webpacpro':
            return webpacpro.LibraryBot(self.library.get_catalog_url(), self.patronid, password, name)
        if self.library.get_library_system() == 'polaris':
            return polaris.LibraryBot(self.library.get_catalog_url(), self.patronid, password, name)
        if self.library.get_library_system() == 'koha':
            return koha.LibraryBot(self.library.get_catalog_url(), self.patronid, password, name)

    def items_out(self, password, patron_name):
        bot = self.get_bot(password, patron_name)
        checkedout = []
        checkedout = bot.itemsOut()
        checkedoutlist = checkedout.values();
        #print "json=" + json.dumps(checkedoutlist, cls=domain.ItemEncoder)
        checkedoutlist.sort(key=lambda item: (item.dueDate, item.title))
        return checkedoutlist


    def get_items(self, password, name, asof_date, check_cache=True, lastchecked_jscompat=True):
        # get items from cache
        asof_date = asof_date.replace(microsecond=0)
        if check_cache == True:
            if password == self.pin:
                if asof_date<=self.lastchecked:
                    # return as a list not QuerySet to make JSON serialization consistent
                    items = Item.objects.filter(patron=self, asof=asof_date.date())
                    #turn the django query result into a regular list
                    item_list = []
                    item_list.extend(items)
                    logging.info('returning cached items of length: ' + str(len(items)))
                    return item_list
            else:
                logging.warn('password does not match for %s', self.patronid)


        # get items from library and update cache
        items = self.items_out(password, name)
        logging.info('remote library call for patron ' + self.patronid + ' items len=' + str(len(items)) + ' asof_date=' + str(asof_date) + ' self.lastchecked=' + str(self.lastchecked))
        if lastchecked_jscompat: # google gadget expected to control the asof_date
            self.lastchecked = asof_date
        else: #website does not
            self.lastchecked = datetime.datetime.now()
        self.save()
        self.update_items(items, asof_date.date())
        return items

    def get_items_max_cache(self):
        midnight = datetime.datetime.now()
        midnight = midnight.replace(hour=0, minute=0)
        return self.get_items(password=self.pin, name=self.name, asof_date=midnight, lastchecked_jscompat=False)

    def get_items_fresh(self):
        midnight = datetime.datetime.now()
        midnight = midnight.replace(hour=0, minute=0)
        return self.get_items(password=self.pin, name=self.name, asof_date=datetime.datetime.now(), check_cache=False, lastchecked_jscompat=False)

    def renew_items(self, password, name, titles):
        bot = self.get_bot(password, name)
        renewedItems = []
        renewedItems = bot.renew(titles)
        renewedItemsList = renewedItems.values();
        renewedItemsList.sort(key=lambda obj:obj.dueDate)
        self.update_items(renewedItemsList, datetime.date.today())
        return renewedItemsList

    def update_items(self, items, asof=datetime.date.today()):
        if self.save_history == False:
            Item.objects.filter(patron=self).delete()
        for item in items:
            logging.debug(item.title)
            item.asof = datetime.date.today()
            item.id
            item.patron = self
            item.save()



class Item(models.Model):
    patron = models.ForeignKey(Patron)
    title = models.CharField(max_length=1024)
    author = models.CharField(max_length=1024, null=True, blank=True)
    outDate =  models.DateField(null=True, blank=True)
    dueDate = models.DateField(null=True, blank=True)
    timesRenewed = models.SmallIntegerField(null=True, blank=True)
    isbn = models.CharField(max_length=25, null=True, blank=True)
    asof = models.DateField()

    # These fields are transient and shouldn't be persisted to DB
    renewitemkeys = None
    renewalError = None
    renewed = None
    renewable = None
    renew_url = None


class AccessLog(models.Model):
    user = models.ForeignKey(User, editable=False)
    patron = models.ForeignKey(Patron, editable=False)
    library = models.ForeignKey(Library, editable=False)
    renewed_count = models.IntegerField(null=True)
    almost_due_count = models.IntegerField(null=True)
    overdue_count = models.IntegerField(null=True)
    viewfunc = models.CharField(max_length=50)
    error = models.CharField(max_length=150, null=True, blank=True)
    error_stacktrace = models.CharField(max_length=3000, null=True, blank=True)
    date = models.DateField(auto_now=True, null=True)


class LibraryRequest(models.Model):
    user = models.ForeignKey(User, editable=False, null=True) #added later, so making it nullable for easier migration
    libraryname = models.CharField('Name of library', blank=False, max_length=200)
    catalogurl = models.CharField('Library account web page', blank=False, max_length=200) #help_text='Usually you can find this by clicking "My Account" on your library\'s web site.  Then copy and paste the URL here.'
    name = models.CharField('Name on library card', max_length=60, blank=True)
    patronid = models.CharField('Card number', max_length=40, blank=True)
    password = models.CharField('Library web site password',  max_length=20, blank=True)

librarygadget/templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
	<meta content="Never pay another library fine - auto-renewals, reminders, and more." name="description" />
 	<link href="/site_media/librarygadget.css" rel="stylesheet" type="text/css" /> 
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<link ref="SHORTCUT ICON" href="http://www.librarygadget.com/images/librarygadget.ico" />
	{% block head %} {% endblock %}
</head>
<body>

<div class="header">
	
	<div class="logo">
		<a href="/"><img src="/site_media/staring_at_a_book.png" alt="Library Gadget logo" /></a>	
		<h1><a href="/">Library Gadget</a></h1>
	</div>
	<div class="sitenav">
		{% if user.is_authenticated %}
			<a href="{% url checked_out %}">Checked Out</a>
			&bull;
			<a href="{% url profile %}">Account</a>
			&bull;
			<a href="{% url django.contrib.auth.views.logout %}">Sign Out</a>
		{% else %}
			<a href="{% url pricing_plans %}">Pricing</a>
            &bull;
            <a href="{% url django.contrib.auth.views.login %}">Log In</a>

		{% endif %}
	</div>	
</div>




<div class="contentbox">
		{% block content %} {% endblock %}
</div>

<div class="footer">
&copy; 2014 &bull;
<a href="{% url about %}">About</a> &bull; 
<a href="{% url privacy %}">Privacy</a>
</div>

<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
var pageTracker = _gat._getTracker("UA-5196144-1");
pageTracker._trackPageview();
</script>

</body>
</html>

librarygadget/templates/checkedout.html
{% extends "base.html" %}

{% block head %}
<title>Library Gadget: Checked Out Items</title>
<script type="text/javascript" src="/site_media/librarygadget.js"></script>
<script type="text/javascript">
  $(document).ready(function() {  
	$("#items").dataTable(
            {"bPaginate": false,
             "bAutoWidth": false,
              bSort: false,
             "aoColumns" : [
                { sWidth: '90px' },
                { sWidth: '600px' }
               ]
            });

    {% include "useraccounts.js" %}
  });
</script>



{% endblock %}

{% block content %} 
        <div id="fb-root"></div>
        <script>(function(d, s, id) {
          var js, fjs = d.getElementsByTagName(s)[0];
          if (d.getElementById(id)) {return;}
          js = d.createElement(s); js.id = id;
          js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=63108621411";
          fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));</script>
    
     {% if patrons|length > 0 %}
     <div class="section">
     <p class="error">Unable to login to these library accounts.</p>

        {% include "useraccounts.html" %}

         Try the following steps.
         <ul>
             <li>Make sure you can log into your library's website</li>
             <li><a href="{% url profile %}">Correct</a>  your card information</li>
             <li><a href="{% url about %}">Report a problem</a></li>

         </ul>
    </div>
    {% endif %}

	<div class="section">

    {% if items|length > 0 and patrons|length == 0 %}
        <table id="items">
            <thead>
             <tr>
                <td class="noborder">Due Date</td>
                <td class="noborder">Title</td>
                
             </tr>
            </thead>
            <tbody>
            {% for item in items  %}

                <tr {% if item.overdue %}class="overdue"{% endif %}>
                    <td>{{ item.dueDate }}</td>
                    <td class="title_column">
                        <a target="_blank" href="{{ item.amazon_url }}">{{ item.short_title }}</a>
                    </td>
                    
                </tr>

            {% endfor %}
            </tbody>
        </table>

    {% endif %}

    <p>{{ message }}</p>

    {% if all_patrons|length == 0 %}
        <p>
        First you need to <a href="{% url libraries %}">add a library card</a>.
        </p>
    {% endif %}

	</div>

    {% if free %}
    <div class="section">
        <a class="fancy_button" style="margin-bottom: 25px; clear: both;" href="{% url profile %}">
            <span style="background-color: #070;">Auto-renewals and more...</span>
        </a>

    </div>
    {% endif %}
	
{% endblock %}

librarygadget/templates/forlibraries.html
{% extends "base.html" %}

{% block head %}
<title>Library Gadget: For libraries</title>

{% endblock %}

{% block content %}

	<div class="section">
	<h3>Love your power users</h3>
        <p>


        </p>

     </div>


{% endblock %}

librarygadget/templates/home.html
{% extends "base.html" %}

{% block head %}
<title>Library Gadget: For busy people who love the library</title>

{% endblock %}

{% block content %}
	<div class="section">
	<h3>For busy people who love the library</h3>
        <p>
            <ul>
                <li>One easy place to see what you've borrowed, even across multiple cards</li>
                <li>Auto-renew items before they're due</li>
                <li>Email notifications for items that can't be auto-renewed</li>
                <li>Daily email reminders about any overdue items</li>

            </ul>

        </p>

     </div>
     <div class="section">
     <h3>No more library fines</h3>

        <p>
            The more you borrow, the faster overdue fines can accrue. Library Gadget keeps on top of it for you.
        </p>

    </div>


	<div class="section">
	<h3>Hundreds of libraries</h3>
	<p>Check our <a href="{% url librarybot.viewsui.libraries %}">list of libraries</a> to see if yours is supported.
	</p>

	</div>


    <div class="section">
        <a class="fancy_button" style="margin-bottom: 25px; clear: both;" href="{% url pricing_plans %}">
            <span style="background-color: #070;">Sign Up</span>
        </a>
    </div>

    <div class="section">
        <h3>What people are saying</h3>

        <p>"Fantastic. Incredibly useful, and the maintainer is very, very fast about adding new libraries.
            I definitely recommend this for anyone who reads a lot."</p>

        <p>"We have four library cards between the wife kids & I, this helps keep it all straight, thanks!"</p>

        <p>"I have been looking everywhere for this kind of service ever since shelling out $15 for an overdue library book.
            In fact, this just saved me from paying another fine as it showed several books that were due today."</p>

    </div>


{% endblock %}

librarygadget/templates/initialpayment.html
{% extends "base.html" %}

{% block head %}
<title>Library Gadget: Payment</title>
{% endblock %}

{% block content %} 


        <div class="section">
        <h3>Payment</h3>

        <p>
          <ul>
            <li>Only {{ upgrade.total_cost }}/year</li>
            <li>Email reminder before items are due</li>
            <li>Daily email reminder about any overdue items</li>
            <li>Automatically renew items for extended checkout periods</li>
        </ul>
        </p>

         </div>

        {% include "payment.html" %}

{% endblock %}

librarygadget/templates/libraries.html
{% extends "base.html" %}

{% block head %}
<title>Library Gadget: Libraries</title>
<script type="text/javascript" src="/site_media/librarygadget.js"></script>
<script type="text/javascript">
  $(document).ready(function() {  
	$("#libraries").dataTable({"bPaginate": false});
  });
</script>


{% endblock %}

{% block content %} 
	
	<table id="libraries" class="libraries">
		<thead>
			<tr>
				<th/>
				<th/>
				<th/>
			</tr>
		</thead>
		{% for library in libraries %}			
			<tr>
				<td><a href="{% url add_account library_id=library.id %}">Add</a></td>
				<td>{{ library.state }}</td>
				<td>{{ library.name }}</td>			
			</tr>
		{% endfor %}
    </table>

	
	<h3>Oh no, my library isn't listed!</h3>
    <p><a href="{%  url library_request %}">Request </a> a new library.</p>
	
	
{% endblock %}

librarygadget/templates/libraryaccount.html
{% extends "base.html" %}

{% block head %}
<title>Library Gadget: Library Account</title>
<script type="text/javascript" src="/site_media/librarygadget.js"></script>
<script type="text/javascript">
  $(document).ready(function() {
	$('p[pin_required="False"]')
        .hide()
        .find("input")
            .val("na");

      {% include "useraccounts.js" %}
  });
</script>



{% endblock %}

{% block content %} 
	
	<div class="section">
	<h3>{{ library.name }}</h3>
	
	{{ form.non_field_errors }}
	<form id='add_account' method='POST'>
		{% csrf_token %}
		<p>
            {{ form.name.errors }}
            <label for="id_name">Name on library card:</label>
            {{ form.name }}
         </p>
        <p>
            {{ form.patronid.errors }}
            <label for="id_patronid">Library card number:</label>
            {{ form.patronid }}
        </p>
        <p pin_required="{{ library.pin_required }}">
            {{ form.pin.errors }}
            <label for="id_pin">Library website password:</label>
            {{ form.pin }}
        </p>
		<p>
		<input id="addaccountbtn" class="button" type="submit" value="Add Card"/>
        </p>
	</form>
	<p>Choose <a href="{% url librarybot.viewsui.libraries %}">another library</a>.
	{% if free and patrons|length > 0 %}
		<p>Auto-renew materials for only {{ upgrade.total_cost }}.
            Click <a href="{% url profile %}">here</a> after adding your cards.</p>
	{% endif %}	
	</p>
	</div>
	
	
	<div class="section">
		{% include "useraccounts.html" %}
	</div>
	
{% endblock %}

librarygadget/templates/libraryrequest.html
{% extends "base.html" %}

{% block head %}
<title>Library Gadget: Library Request</title>
<script type="text/javascript" src="/site_media/librarygadget.js"></script>


</script>
{% endblock %}

{% block content %}
    <div class="section">
    <p>
    Most libraries can be added within a day or two. Others, however, use uncommon systems and may take
    much longer (if ever). I'll try to get back to you either way within a week.
    </p>
    </div>

    <div class="section">

    {{ form.non_field_errors }}
	<form id="requestform" method="POST">
        {% csrf_token %}
        <p>{{ form.libraryname.errors }} {{ form.libraryname.label_tag }} {{ form.libraryname }}</p>
        <p>{{ form.catalogurl.errors }} {{ form.catalogurl.label_tag }} {{ form.catalogurl }}</p>

        <div id="optional">
        <p>Optional, but extremely helpful information.
        </p>
        <p>{{ form.name.errors }} {{ form.name.label_tag }} {{ form.name }}</p>
        <p>{{ form.patronid.errors }} {{ form.patronid.label_tag }} {{ form.patronid }}</p>
        <p>{{ form.password.errors }}{{ form.password.label_tag }} {{ form.password }}</p>
        <p>{{ form.renewal_item.errors }}{{ form.renewal_item.label_tag }} {{ form.renewal_item }}</p>
        </div>
		
		<input type="submit" class="button" value="Request Library"/>
	</form>




    </div>
{% endblock %}

librarygadget/templates/libraryrequestthanks.html
{% extends "base.html" %}

{% block head %}
<title>Library Gadget: Request submitted</title>
{% endblock %}

{% block content %} 
	
	<div class="section">
	<h3>Thanks!</h3>
	
	<p>
	Your request has been received. You can expect to hear back within a week.
	</p>
	
	</div>
{% endblock %}

librarygadget/templates/orderreturn.html
{% extends "base.html" %}

{% block head %}
<title>Library Gadget: Activation Successful</title>
{% endblock %}

{% block content %} 
	
	<div class="section">
	<h3>Thanks!</h3>
	
	<p>
	Thanks for activating your premium Library Gadget account! Your confirmation number is <strong>{{ paypal_order.tx }}</strong>.
	</p>
    
    <p>
    <p><a href="{% url libraries %}">Add your library cards</a></p>

    </p>
	
	</div>
{% endblock %}

librarygadget/templates/pricingplans.html
{% extends "base.html" %}

{% block head %}
<title>Library Gadget: Pricing Plans</title>
{% endblock %}

{% block content %} 


    <div class="section">
	{% include "pricing.html" %}
    </div>


	
{% endblock %}

librarygadget/templates/privacy.html
{% extends "base.html" %}

{% block head %}
<title>Library Gadget: Privacy</title>
{% endblock %}

{% block content %} 

<p>I won't use your personal details for any reason other than to fulfill your requests or to 
send email alerts or service updates. I won't disclose personal details to a third party 
unless you explicitly initiate the action (for example, by clicking a link to share a library item on Facebook) 
or unless ordered to do so by a court. 
</p>

<p>Links to Amazon.com contain an embedded Library Gadget affiliate code. Affiliate payments help support
Library Gadget at no cost to you.</p>

<p>It goes without saying that I'll never sell your email address to spammers. But I'll say it anyway.</p>
    
<p>- Scott Peterson</p>

{% endblock %}

librarygadget/templates/profile.html
{% extends "base.html" %}

{% block head %}
<title>Library Gadget: Account</title>
<script type="text/javascript" src="/site_media/librarygadget.js"></script>
<script type="text/javascript">
  $(document).ready(function() {  
    {% include "useraccounts.js" %}
  });
</script>
{% endblock %}

{% block content %} 


	
    {% if patrons|length > 0 %}

        {% if free %}
            <div class="section">
            <h3>Upgrade your Account</h3>

            <p>
              <ul>
                <li>Only {{ upgrade.total_cost }}/year</li>
                <li>Email reminder before items are due</li>
                <li>Daily email reminder about any overdue items</li>
                <li>Automatically renew items for extended checkout periods</li>
            </ul>
            </p>



             </div>

            {% include "payment.html" %}

        {% else %}
            
            <div class="section">
            <h3>Account</h3>
            <p>You have the premium plan.<p>
            </div>
        {% endif %}
    {% endif %}

    <div class="section">
	{% include "useraccounts.html" %}

	 <p><a href="{% url libraries %}">Add a library card</a></p>

     <p><a href="http://www.google.com/ig/directory?type=gadgets&url=www.librarygadget.com/gadgets/igoogle/librarygadget.xml">Add to iGoogle</a>
        </p>
    </div>
	
{% endblock %}

librarygadget/templates/useraccounts.html

<table id="accounts" cellspacing="2">

	{% if patrons|length > 0 %}
		<thead>
			<tr>
			<td>Library</td>
			<td>Card</td>
			<td>Cardholder</td>
			</tr>
		</thead>
		<tbody>
		{% for patron in patrons %}		
			<tr>

				<td><a href="{{ patron.library.get_catalog_url }}">{{ patron.library.name }}</a></td>
				<td>{{ patron.patronid }}</td>	
				<td>{{ patron.name }}</td>
                <td>
                    <form action="{% url delete_account %}" method="POST">
                  		{% csrf_token %}
			            <input type="hidden" name="return" value="{{ return }}"/>
                        <input type="hidden" name="patronid" value="{{ patron.patronid }}"/>
                         <a href="#" class="removeaccount">X</a>
				    </form>
                </td>
			</tr>

		{% endfor %}
	{% endif %}
	
	</tbody>
</table>


